version: '3'
services:
  postgres:
    image: "postgres:14"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=purchase     
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data  

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "teste@wex.com"
      PGADMIN_DEFAULT_PASSWORD: "testewex"
    ports:
      - "54321:80"
    depends_on:
      - postgres

