services:
  postgres:
    image: postgres:15
    container_name: postgres_container_wex
    environment:
      POSTGRES_USER: wex
      POSTGRES_PASSWORD: wex
      POSTGRES_DB: wex    
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data  

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "teste@wex.com"
      PGADMIN_DEFAULT_PASSWORD: "testewex"
    ports:
      - "54321:80"
    depends_on:
      - postgres
volumes:
  postgres_data:
