package utils

type Currencies struct {
	Currencies map[string]string `json:"currencies"`
}

func NewCurrencies() *Currencies {
	return &Currencies{
		Currencies: map[string]string{
			"Afghanistan":               "Afghanistan-Afghani",
			"Albania":                   "Albania-Lek",
			"Algeria":                   "Algeria-Dinar",
			"Angola":                    "Angola-Kwanza",
			"Antigua":                   "Antigua & Barbuda-E. Caribbean Dollar",
			"Argentina":                 "Argentina-Peso",
			"Armenia":                   "Armenia-Dram",
			"Australia":                 "Australia-Dollar",
			"Azerbaijan":                "Azerbaijan-Manat",
			"Bahamas":                   "Bahamas-Dollar",
			"Bahrain":                   "Bahrain-Dinar",
			"Bangladesh":                "Bangladesh-Taka",
			"Barbados":                  "Barbados-Dollar",
			"Belarus":                   "Belarus-New Ruble",
			"Belize":                    "Belize-Dollar",
			"Benin":                     "Benin-CFA Franc",
			"Bermuda":                   "Bermuda-Dollar",
			"Bolivia":                   "Bolivia-Boliviano",
			"Bosnia":                    "Bosnia-Marka",
			"Botswana":                  "Botswana-Pula",
			"Brazil":                    "Brazil-Real",
			"Brunei":                    "Brunei-Dollar",
			"Bulgaria":                  "Bulgaria-Lev New",
			"Burkina":                   "Burkina Faso-CFA Franc",
			"Burma":                     "Burma-Kyat",
			"Burundi":                   "Burundi-Franc",
			"Cambodia":                  "Cambodia-Riel",
			"Cameroon":                  "Cameroon-CFA Franc",
			"Canada":                    "Canada-Dollar",
			"Cape":                      "Cape Verde-Escudo",
			"Cayman":                    "Cayman Islands-Dollar",
			"Central_African_Rep_Franc": "Central African Rep.-CFA Franc",
			"Chad":                      "Chad-CFA Franc",
			"Chile":                     "Chile-Peso",
			"China":                     "China-Renminbi",
			"Colombia":                  "Colombia-Peso",
			"Comoros":                   "Comoros-Franc",
			"Congo":                     "Congo-CFA Franc",
			"Costa_Rica":                "Costa Rica-Colon",
			"Cote_Divoire":              "Cote D'ivoire-CFA Franc",
			"Croatia_Euro":              "Croatia-Euro",
			"Croatia_KUNA":              "Croatia-KUNA",
			"Cuba_Chavito":              "Cuba-Chavito",
			"Cuba_Peso":                 "Cuba-Peso",
			"Cyprus":                    "Cyprus-Euro",
			"Czech":                     "Czech Republic-Koruna",
			"Dem":                       "Dem. Rep. of Congo-Congolese Franc",
			"Denmark":                   "Denmark-Krone",
			"Djibouti":                  "Djibouti-Franc",
			"Dominican":                 "Dominican Republic-Peso",
			"Ecuador":                   "Ecuador-Dolares",
			"Egypt":                     "Egypt-Pound",
			"El_Salvador":               "El Salvador-Dollar",
			"Equatorial":                "Equatorial Guinea-CFA Franc",
			"Eritrea":                   "Eritrea-Nakfa",
			"Eswatini":                  "Eswatini-Lilangeni",
			"Ethiopia":                  "Ethiopia-Birr",
			"Euro":                      "Euro Zone-Euro",
			"Fiji":                      "Fiji-Dollar",
			"France":                    "France-Euro",
			"Gabon":                     "Gabon-CFA Franc",
			"Gambia":                    "Gambia-Dalasi",
			"Georgia":                   "Georgia-Lari",
			"Ghana":                     "Ghana-Cedi",
			"Grenada":                   "Grenada-E.Caribbean Dollar",
			"Guatemala":                 "Guatemala-Quentzal",
			"Guinea_Bissau":             "Guinea Bissau-CFA Franc",
			"Guinea_Franc":              "Guinea-Franc",
			"Guyana":                    "Guyana-Dollar",
			"Haiti":                     "Haiti-Gourde",
			"Honduras":                  "Honduras-Lempira",
			"Hong_Kong":                 "Hong Kong-Dollar",
			"Hungary":                   "Hungary-Forint",
			"Iceland":                   "Iceland-Krona",
			"India":                     "India-Rupee",
			"Indonesia":                 "Indonesia-Rupiah",
			"Iran":                      "Iran-Rial",
			"Iraq":                      "Iraq-Dinar",
			"Israel":                    "Israel-Shekel",
			"Jamaica":                   "Jamaica-Dollar",
			"Japan":                     "Japan-Yen",
			"Jordan":                    "Jordan-Dinar",
			"Kazakhstan":                "Kazakhstan-Tenge",
			"Kenya":                     "Kenya-Shilling",
			"Korea":                     "Korea-Won",
			"Kuwait":                    "Kuwait-Dinar",
			"Kyrgyzstan":                "Kyrgyzstan-Som",
			"Lesotho":                   "Lesotho-Maloti",
			"Liberia":                   "Liberia-Dollar",
			"Libya":                     "Libya-Dinar",
			"Lithuania":                 "Lithuania-Euro",
			"Madagascar":                "Madagascar-Ariary",
			"Malawi":                    "Malawi-Kwacha",
			"Malaysia":                  "Malaysia-Ringgit",
			"Maldives":                  "Maldives-Rufiyaa",
			"Mali":                      "Mali-CFA Franc",
			"Marshall_Islands":          "Marshall Islands-U.S. Dollar",
			"Mauritania":                "Mauritania-Ouguiya",
			"Mauritius":                 "Mauritius-Rupee",
			"Mexico":                    "Mexico-Peso",
			"Micronesia":                "Micronesia-U.S. Dollar",
			"Moldova":                   "Moldova-LEU",
			"Mongolia":                  "Mongolia-Tugrik",
			"Morocco":                   "Morocco-Dirham",
			"Mozambique":                "Mozambique-Metical",
			"Myanmar":                   "Myanmar-Kyat",
			"Nambia":                    "Nambia-Dollar",
			"Nepal":                     "Nepal-Rupee",
			"Netherlands_Antilles":      "Netherlands Antilles-Guilder",
			"Netherlands_Euro":          "Netherlands-Euro",
			"New_Zealand":               "New Zealand-Dollar",
			"Nicaragua":                 "Nicaragua-Cordoba",
			"Niger":                     "Niger-CFA Franc",
			"Nigeria":                   "Nigeria-Naira",
			"Norway":                    "Norway-Krone",
			"Oman":                      "Oman-Rial",
			"Pakistan":                  "Pakistan-Rupee",
			"Palau":                     "Palau-Dollar",
			"Panama":                    "Panama-Dolares",
			"Papua_New_Guinea":          "Papua New Guinea-Kina",
			"Paraguay":                  "Paraguay-Guarani",
			"Peru":                      "Peru-Sol",
			"Philippines":               "Philippines-Peso",
			"Poland":                    "Poland-Zloty",
			"Qatar":                     "Qatar-Riyal",
			"Rep_Macedonia":             "Rep. of N. Macedonia-Denar",
			"Romania":                   "Romania-New Leu",
			"Sao_Tome_Principe":         "Sao Tome & Principe-New Dobras",
			"Saudi":                     "Saudi Arabia-Riyal",
			"Senegal":                   "Senegal-CFA Franc",
			"Serbia":                    "Serbia-Dinar",
			"Seychelles":                "Seychelles-Rupee",
			"Sierra_Leone":              "Sierra Leone-Leone",
			"Sierra_Leone_Old":          "Sierra Leone-Old Leone",
			"Singapore":                 "Singapore-Dollar",
			"Solomon":                   "Solomon Islands-Dollar",
			"Somali":                    "Somali-Shilling",
			"South_Africa":              "South Africa-Rand",
			"South_Sudan":               "South Sudan-Sudanese Pound",
			"Sri_Lanka":                 "Sri Lanka-Rupee",
			"St_Lucia":                  "St. Lucia-E. Caribbean Dollar",
			"Sudan":                     "Sudan-Pound",
			"Suriname":                  "Suriname-Dollar",
			"Sweden":                    "Sweden-Krona",
			"Switzerland":               "Switzerland-Franc",
			"Syria":                     "Syria-Pound",
			"Taiwan":                    "Taiwan-Dollar",
			"Tajikistan":                "Tajikistan-Somoni",
			"Tanzania":                  "Tanzania-Shilling",
			"Thailand":                  "Thailand-Baht",
			"Timor":                     "Timor-Leste-Dili",
			"Togo":                      "Togo-CFA Franc",
			"Tonga":                     "Tonga-Pa'anga",
			"Trinidad":                  "Trinidad & Tobago-Dollar",
			"Tunisia":                   "Tunisia-Dinar",
			"Turkey":                    "Turkey-New Lira",
			"Turkmenistan":              "Turkmenistan-New Manat",
			"Uganda":                    "Uganda-Shilling",
			"Ukraine":                   "Ukraine-Hryvnia",
			"United_Arab":               "United Arab Emirates-Dirham",
			"United_Kingdom":            "United Kingdom-Pound",
			"Uruguay":                   "Uruguay-Peso",
			"Uzbekistan":                "Uzbekistan-Som",
			"Vanuatu":                   "Vanuatu-Vatu",
			"Venezuela_Bolivar":         "Venezuela-Bolivar Soberano",
			"Venezuela_Fuerte":          "Venezuela-Fuerte (OLD)",
			"Vietnam":                   "Vietnam-Dong",
			"Western_Samoa":             "Western Samoa-Tala",
			"Yemen":                     "Yemen-Rial",
			"Zambia":                    "Zambia-New Kwacha",
			"Zimbabwe_Gold":             "Zimbabwe-Gold",
			"Zimbabwe_RTGS":             "Zimbabwe-RTGS",
		},
	}
}
